ILoveEnglishSchool/Models/Lesson.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ILoveEnglishSchool.Models {
    public class Lesson {
        [Key]
        public int LessonId { get; set; }
        public Level Level { get; set; } = Level.None;
        public int LessonNumber { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public ICollection<Part> Parts { get; set; } = new List<Part>();
    }
}

ILoveEnglishSchool/Models/LessonType.cs
namespace ILoveEnglishSchool.Models {
    public enum LessonType {
        Combined,
        Grammar,
        Listening,
        Speaking,
        Vocabulary,
        Video
    }
}

ILoveEnglishSchool/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ILoveEnglishSchool.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ILoveEnglishSchool.Data;
using ILoveEnglishSchool.Models;
using ILoveEnglishSchool.Controllers;

namespace ILoveEnglishSchool.Controllers
{
    public class PartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PartController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Part
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Parts.Where(p => p.LessonId.Equals(id)).Include(p=>p.Lesson);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Part/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.PartModulesEnumerable.Include(p=>p.Part)
                .Include(p => p.Part.Lesson).ToListAsync();
            if (part == null)
            {
                return NotFound();
            }

            return View(part.Where(p=>p.PartId.Equals(id)));
        }

        // GET: Part/Create
        public IActionResult Create(int id) {
            ViewData["ID"] = id;
            ViewData["LessonId"] = new SelectList(_context.Lessons, "LessonId", "LessonId");
            return View();
        }

        // POST: Part/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PartId,WelcomeImage,Name,LessonId,Type")] Part part)
        {
            if (ModelState.IsValid)
            {
                _context.Add(part);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"PartModules", new {id = part.PartId});
            }
            ViewData["LessonId"] = new SelectList(_context.Lessons, "LessonId", "LessonId", part.LessonId);
            return View(part);
        }

        // GET: Part/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.Parts.FindAsync(id);
            if (part == null)
            {
                return NotFound();
            }

            ViewData["LessonId"] =await _context.Lessons.ToListAsync();
            return View(part);
        }

        // POST: Part/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PartId,WelcomeImage,Name,LessonId,Type")] Part part)
        {
            if (id != part.PartId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(part);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartExists(part.PartId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new {id = part.LessonId});
            }
            ViewData["LessonId"] = await _context.Lessons.ToListAsync();
            return View(part);
        }

        // GET: Part/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var part = await _context.Parts
                .Include(p => p.Lesson)
                .FirstOrDefaultAsync(m => m.PartId == id);
            if (part == null)
            {
                return NotFound();
            }

            return View(part);
        }

        // POST: Part/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var part = await _context.Parts.FindAsync(id);
            _context.Parts.Remove(part);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index),new{id=id});
        }

        private bool PartExists(int id)
        {
            return _context.Parts.Any(e => e.PartId == id);
        }
    }
}

ILoveEnglishSchool/Views/Lesson/Create.cshtml
@model ILoveEnglishSchool.Models.Lesson

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
<h1 class="jumbotron" style="background: linear-gradient(43deg, #add681 0%, #bbedfb);color: rgb(0,0,0); height: 40px;justify-content: center; width: 100pc; margin-left: -10pc">
    Lesson creator (Step 1 of 3)
</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LessonNumber" class="control-label">Lesson Number</label>
                <input asp-for="LessonNumber" class="form-control" />
                <span asp-validation-for="LessonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label"></label>
                <input asp-for="Topic" class="form-control" required />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <select class="custom-select" asp-for="Level" asp-items="Html.GetEnumSelectList<Level>()"></select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" required />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn" style="background-color: #8aacc8;" />
                <a asp-action="Index" class="btn" style="background-color: #add681;">Back to List</a>
            </div>
        </form>
    </div>
</div>

</body>
</html>

ILoveEnglishSchool/Views/Lesson/Delete.cshtml
@model ILoveEnglishSchool.Models.Lesson

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
<h1 class="jumbotron" style="background: linear-gradient(43deg, #add681 0%, #bbedfb);color: rgb(0,0,0); height: 40px;justify-content: center; width: 100pc; margin-left: -10pc">
    Lesson delete
</h1>
<h1 class="text-danger">Are you sure you want to delete this?</h1>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic)
        </dd>
        <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Level)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Level)
                </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LessonId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn" style="background-color: #add681;">Back to List</a>
    </form>
</div>
</body>
</html>

ILoveEnglishSchool/Views/Lesson/Details.cshtml
@model ILoveEnglishSchool.Models.Lesson

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LessonNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LessonNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LessonId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

ILoveEnglishSchool/Views/Lesson/Edit.cshtml
@model ILoveEnglishSchool.Models.Lesson

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h1 class="jumbotron" style="background: linear-gradient(43deg, #add681 0%, #bbedfb);color: rgb(0,0,0); height: 40px;justify-content: center; width: 100pc; margin-left: -10pc">
    Lesson editor
</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LessonId" />
            <div class="form-group">
                <label asp-for="LessonNumber" class="control-label"></label>
                <input asp-for="LessonNumber" class="form-control" />
                <span asp-validation-for="LessonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label"></label>
                <input asp-for="Topic" class="form-control" />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <select class="custom-select" asp-for="Level" asp-items="Html.GetEnumSelectList<Level>()"></select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn" style="background-color: #8aacc8;" />
                <a asp-action="Index" class="btn" style="background-color: #add681;">Back to List</a>
            </div>
        </form>
    </div>
</div>

</body>
</html>

ILoveEnglishSchool/Views/Lesson/Index.cshtml
@model IEnumerable<ILoveEnglishSchool.Models.Lesson>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body style="justify-content: center;">
<h1 class="jumbotron" style="background: linear-gradient(43deg, #add681 0%, #bbedfb);color: rgb(0,0,0); height: 40px;justify-content: center; width: 100pc; margin-left: -10pc">
    Lesson explorer
</h1>
<p>
    <a asp-action="Create" class="btn" style="background-color: #add681;">Create Lesson</a>
</p>
@using (Html.BeginForm()) {
    <p class="container row">
        <input type="search" class="form-control col-3 m-0 p-1" name="SearchString" placeholder="Looking for lesson?" style="font-family: Menlo,serif; margin-right: 0;">
        <button type="submit" class="btn btn-success form-control col-auto m-0" style="width: 50px; margin-left: 0">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
            </svg></button>
    </p>
}
<table class="table table-striped">
    <thead>
    <tr class="col-12" style="background-color: #bbdefb;">
        <th>
            ID
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th >
        <th>
            @Html.DisplayNameFor(model => model.Level)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody style="background-color: #eeffff;">
    @foreach (var item in Model) {
        <tr>
            <td class="text-danger font-weight-bold">
                Lesson @Html.DisplayFor(modelItem => item.LessonNumber)
            </td>
            <td class="text-danger font-weight-bold">
                @{
                    try {
                        if (item.Topic.Contains("Food")||item.Topic.Contains("Kitchen")||item.Topic.Contains("Drinks")) {
                            @Html.DisplayFor(modelItem => item.Topic)
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-egg-fried" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M13.665 6.113a1 1 0 0 1-.667-.977L13 5a4 4 0 0 0-6.483-3.136 1 1 0 0 1-.8.2 4 4 0 0 0-3.693 6.61 1 1 0 0 1 .2 1 4 4 0 0 0 6.67 4.087 1 1 0 0 1 1.262-.152 2.5 2.5 0 0 0 3.715-2.905 1 1 0 0 1 .341-1.113 2.001 2.001 0 0 0-.547-3.478zM14 5c0 .057 0 .113-.003.17a3.001 3.001 0 0 1 .822 5.216 3.5 3.5 0 0 1-5.201 4.065 5 5 0 0 1-8.336-5.109A5 5 0 0 1 5.896 1.08 5 5 0 0 1 14 5z"/>
                                <circle cx="8" cy="8" r="3"/>
                            </svg>
                        }
                        else if (item.Topic.ToLower().Contains("Free Time".ToLower()) || item.Topic.Contains("Weather") || item.Topic.Contains("Space")) {
                            @Html.DisplayFor(modelItem => item.Topic)
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-brightness-high" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
                            </svg>
                        }
                        else if (item.Topic.ToLower().Contains("Book".ToLower()) ||item.Topic.ToLower().Contains("Literature".ToLower())) {
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                            </svg>
                            @Html.DisplayFor(modelItem => item.Topic);
                        }
                        else {
                            @Html.DisplayFor(modelItem => item.Topic);
                        }
                    }
                    catch {
                        <p>Error</p>
                    }
                    
                    
                }
            </td>
            <td class="text-success font-weight-bold">
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td class="text-success font-weight-bold">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
            <a asp-action="Index" asp-controller="Part" asp-route-id="@item.LessonId" class="btn" style="background-color: #add681;">Choose</a> |
                <a asp-action="Edit" asp-route-id="@item.LessonId" class="btn" style="background-color: #8aacc8;">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.LessonId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
</body>
</html>